### ISSUE TITLE
Configuring connector livestatus

### ISSUE THREAD

**Issue by sistemmsn** [chriscareycode/nagiostv-react#80]
Is there a reason why the nagiostv can't see it using the livestatus

<img width="800" alt="image" src="https://github.com/chriscareycode/nagiostv-react/assets/38023703/cd305c6d-0597-4da0-997d-444bc298728b">

<img width="400" alt="image" src="https://github.com/chriscareycode/nagiostv-react/assets/38023703/c0f197ec-eb18-48a0-9e76-fff3d0635ed0">

I manually ran the connector and it threw these errors

<img width="913" alt="image" src="https://github.com/chriscareycode/nagiostv-react/assets/38023703/8bea85fd-8ec8-4666-9098-4b700b866888">

**Comment by sistemmsn** [comment]
> error_log

[20-Feb-2024 11:11:22 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:11:22 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:11:22 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:11:22 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:540
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(540): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 540
[20-Feb-2024 11:11:22 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:594
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(594): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 594
[20-Feb-2024 11:11:22 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:11:26 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:594
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(594): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 594
[20-Feb-2024 11:11:26 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:11:26 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:11:26 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:11:26 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:540
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(540): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 540
[20-Feb-2024 11:11:26 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:12:00 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:12:00 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:12:00 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:594
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(594): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 594
[20-Feb-2024 11:12:00 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:12:00 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:540
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(540): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 540
[20-Feb-2024 11:12:00 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:12:25 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:12:25 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:12:25 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:12:25 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:12:25 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:594
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(594): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 594
[20-Feb-2024 11:12:25 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:540
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(540): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 540
[20-Feb-2024 11:12:54 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:12:54 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:13:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:13:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:13:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:13:54 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:13:54 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:14:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:14:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:14:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:14:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:15:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:15:50 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:15:50 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:16:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:16:24 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:16:50 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:16:50 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:16:56 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:16:56 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:17:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:540
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(540): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 540
[20-Feb-2024 11:17:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:483
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(483): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 483
[20-Feb-2024 11:17:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:17:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401
[20-Feb-2024 11:17:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:17:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:594
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(594): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 594
[20-Feb-2024 11:17:32 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:17:32 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:18:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:649
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(649): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 649
[20-Feb-2024 11:18:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:690
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(690): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 690
[20-Feb-2024 11:18:03 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /opt/nagios/share/nagiostv/connectors/livestatus.php:401
Stack trace:
#0 /opt/nagios/share/nagiostv/connectors/livestatus.php(401): join()
#1 {main}
  thrown in /opt/nagios/share/nagiostv/connectors/livestatus.php on line 401

**Comment by NEMSLinux** [comment]
Hi @chriscareycode - and @sistemmsn 

Chris - I encountered this with development for NEMS Linux 1.7, where PHP has been upgraded to 8.2. It's due to join() function deprecation.

Luckily, it's a very easy fix.

Please find all lines within ./connectors/livestatus.php containing `$query = join($query_arr, "\n");`

and replace with:

`$query = implode("\n", $query_arr);`

I'd do a PR but my repo deviates too far from yours, so hopefully the comment helps  :) Thanks!

**Comment by chriscareycode** [comment]
Thanks @NEMSLinux ! super helpful !
This will go out on the next release
